### ISSUE TITLE
Train CycleGAN with my own dataset

### ISSUE THREAD

**Issue by akamob** [look4pritam/ArtificialIntelligence#26]
Hi, Thank you for the great work.

I have created my dataset and uploaded it to my google drive (my dataset was compressed as .zip file).
In the following figure, it seems that I can't download my dataset.
![q1](https://user-images.githubusercontent.com/49118957/176884196-3336949b-0dc7-439f-976d-d66ce34dd306.jpg)

May i have your suggestions to solve this problem? If it is possible that use `keras.utils.get_file` to load .zip file directly?
Any help is much appreciated!

**Comment by look4pritam** [comment]
You will have to use [gdown](https://github.com/wkentaro/gdown) to download files from Google Drive.

**Comment by akamob** [comment]
Hi, Thank you for your reply.

Ok, if I have some new problems then I would contact you again.
Thank you!
